// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD54-fglr01Lvt1t9hhyP36oyRMNK-YCSc',
    appId: '1:167231567979:web:e6b1cc44bf34fede68192e',
    messagingSenderId: '167231567979',
    projectId: 'store-779b7',
    authDomain: 'store-779b7.firebaseapp.com',
    storageBucket: 'store-779b7.firebasestorage.app',
    measurementId: 'G-DK8VK5S21Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcv9tNbk9WYTlgRKr7DA4_lW6SB8_oQl0',
    appId: '1:167231567979:android:12c0aa931b7dabe368192e',
    messagingSenderId: '167231567979',
    projectId: 'store-779b7',
    storageBucket: 'store-779b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEXQ-faCIwaQ7shl_65NVzvrras18EX4Q',
    appId: '1:167231567979:ios:41d22ff0d6a4eea668192e',
    messagingSenderId: '167231567979',
    projectId: 'store-779b7',
    storageBucket: 'store-779b7.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEXQ-faCIwaQ7shl_65NVzvrras18EX4Q',
    appId: '1:167231567979:ios:41d22ff0d6a4eea668192e',
    messagingSenderId: '167231567979',
    projectId: 'store-779b7',
    storageBucket: 'store-779b7.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD54-fglr01Lvt1t9hhyP36oyRMNK-YCSc',
    appId: '1:167231567979:web:49c00abb37ae9ffe68192e',
    messagingSenderId: '167231567979',
    projectId: 'store-779b7',
    authDomain: 'store-779b7.firebaseapp.com',
    storageBucket: 'store-779b7.firebasestorage.app',
    measurementId: 'G-TLXFD555XT',
  );
}
